[package]
name = "rusty-ls"
version = "0.1.3"
edition = "2021"
description = "A replacement for the ls command"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
chrono = "0.4"
libc = "0.2.147"
